---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[ubuntu::default]
  - name: ubuntu-12.04
    run_list:
      - recipe[ubuntu::default]
  - name: centos-7.2
  - name: centos-6.6
  - name: centos-5.11

suites:
  - name: default
    run_list:
      - recipe[logrotate::default]
  - name: definition
    run_list:
      - recipe[fake::definition]
  - name: global
    run_list:
      - recipe[logrotate::global]
